import { Footer } from "@/components";
import "./globals.css";
import { Inter, Cairo } from "next/font/google";
import { PrimeReactProvider, PrimeReactContext } from "primereact/api";
// import "primereact/resources/themes/arya-blue/theme.css";
// import "primereact/resources/themes/vela-green/theme.css";
// import "primereact/resources/themes/soho-light/theme.css";
import "primereact/resources/themes/viva-light/theme.css";
import {
  useTranslations,
  NextIntlClientProvider,
  useMessages,
  useLocale,
} from "next-intl";
import { getLangDir } from "rtl-detect";

const inter = Inter({ subsets: ["latin"] });
const cairo = Cairo({ subsets: ["arabic"] });

export const metadata = {
  title: "ERA TECH-HOUSE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  locale,
}: {
  children: React.ReactNode;
  locale: never;
}) {
  const currentLocale = useLocale();
  const direction = getLangDir(currentLocale);
  const messages = useMessages();

  return (
    <PrimeReactProvider>
      <NextIntlClientProvider locale={locale} messages={messages}>
        <html lang={locale} dir={direction}>
          <body
            className={
              currentLocale === "en" ? inter.className : cairo.className
            }
          >
            <div>{children}</div>
          </body>
        </html>
      </NextIntlClientProvider>
    </PrimeReactProvider>
  );
}
